import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import ts from "typescript";
import { parse } from "yaml";

import { buildEndpointPages } from "../endpoints/buildEndpointPages.js";

/**
 * The generated reference chapters of the book "Build with Parmana"
 * (docs/site/build-book): every endpoint, every SDK method in both
 * languages, and every error code, read from the code itself, so they
 * cannot drift from it. tests/architecture/build-book-reference-up-to-date.test.ts
 * fails when a committed chapter differs from what this builds.
 *
 * Sources:
 * - endpoints: openapi/openapi.bundled.yaml, through buildEndpointPages,
 *   the same reading that makes the REST API pages;
 * - SDK methods: typescript/src/client/ParmanaClient.ts (TypeScript
 *   compiler API) and python/parmana/client.py, with each method's own
 *   doc comment, plus the functions each SDK exports for signing and
 *   verifying;
 * - error codes: every `code` in a response example of the OpenAPI file,
 *   each a real captured response, with its HTTP status.
 */

const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

export const BUILD_BOOK_DIRECTORY = "docs/site/build-book";

export interface GeneratedChapter {
  readonly file: string;
  readonly content: string;
}

const HEADER_NOTE =
  "{/* Generated by scripts/generate-build-book-reference.ts. Do not edit: run `npm run generate:build-book-reference`. */}";

function read(path: string): string {
  return readFileSync(join(repoRoot, path), "utf8");
}

function cell(text: string): string {
  return text
    .replace(/\s+/g, " ")
    .replace(/\\/g, "\\\\")
    .replace(/\|/g, "\\|")
    .trim();
}

function frontMatter(title: string, description: string): string {
  return [
    "---",
    `title: "${title}"`,
    `description: "${description}"`,
    "---",
    "",
  ].join("\n");
}

// -----------------------------------------------------------------------------
// Endpoints
// -----------------------------------------------------------------------------

function endpointsChapter(): GeneratedChapter {
  const pages = buildEndpointPages();
  const groups = new Map<string, typeof pages>();

  for (const page of pages) {
    groups.set(page.group, [...(groups.get(page.group) ?? []), page]);
  }

  const lines = [
    frontMatter(
      "Reference: every endpoint",
      "Every operation of the Parmana REST API, grouped as in the API reference, generated from the OpenAPI file.",
    ),
    HEADER_NOTE,
    "",
    `Every operation the server exposes, ${pages.length} in all, read from \`openapi/openapi.bundled.yaml\`. Tests keep that file equal to the routes the server actually mounts (\`openapi-route-parity.test.ts\`). Each row links to the operation's page, with its schemas and real captured responses.`,
    "",
  ];

  for (const [group, entries] of groups) {
    lines.push(
      `## ${group}`,
      "",
      "| Method | Path | What it does |",
      "| ------ | ---- | ------------ |",
    );

    for (const entry of entries) {
      lines.push(
        `| \`${entry.method}\` | [\`${cell(entry.path)}\`](/${entry.navPath}) | ${cell(entry.description)} |`,
      );
    }

    lines.push("");
  }

  return {
    file: `${BUILD_BOOK_DIRECTORY}/reference-endpoints.mdx`,
    content: lines.join("\n"),
  };
}

// -----------------------------------------------------------------------------
// SDK methods
// -----------------------------------------------------------------------------

interface SdkEntry {
  readonly signature: string;
  readonly summary: string;
}

function firstParagraph(text: string): string {
  const paragraph = text.trim().split(/\n\s*\n/)[0] ?? "";
  return cell(paragraph);
}

function typescriptClientMethods(): SdkEntry[] {
  const path = "typescript/src/client/ParmanaClient.ts";
  const source = ts.createSourceFile(
    path,
    read(path),
    ts.ScriptTarget.Latest,
    true,
  );
  const entries: SdkEntry[] = [];

  source.forEachChild((node) => {
    if (!ts.isClassDeclaration(node) || node.name?.text !== "ParmanaClient")
      return;

    for (const member of node.members) {
      if (!ts.isMethodDeclaration(member) || !ts.isIdentifier(member.name))
        continue;

      const modifiers = ts.getModifiers(member) ?? [];
      if (
        modifiers.some(
          (m) =>
            m.kind === ts.SyntaxKind.PrivateKeyword ||
            m.kind === ts.SyntaxKind.ProtectedKeyword,
        )
      ) {
        continue;
      }

      const parameters = member.parameters
        .map((p) => p.getText(source).replace(/\s+/g, " "))
        .join(", ");
      const returns = member.type
        ? `: ${member.type.getText(source).replace(/\s+/g, " ")}`
        : "";
      const doc = ts
        .getJSDocCommentsAndTags(member)
        .map((d) => (typeof d.comment === "string" ? d.comment : ""))
        .join("\n");

      entries.push({
        signature: `${member.name.text}(${parameters})${returns}`,
        summary: firstParagraph(doc),
      });
    }
  });

  return entries;
}

function typescriptExportedFunctions(): SdkEntry[] {
  const index = read("typescript/src/index.ts");
  const exported = new Set(
    [...index.matchAll(/^\s+([a-z][A-Za-z0-9]*),?$/gm)].map((m) => m[1] ?? ""),
  );
  const entries: SdkEntry[] = [];

  for (const path of [
    "typescript/src/crypto/offline-verifier.ts",
    "typescript/src/crypto/step-up.ts",
    "typescript/src/crypto/approval.ts",
    "typescript/src/crypto/release.ts",
    "typescript/src/crypto/canonical.ts",
  ]) {
    const source = ts.createSourceFile(
      path,
      read(path),
      ts.ScriptTarget.Latest,
      true,
    );

    source.forEachChild((node) => {
      if (!ts.isFunctionDeclaration(node) || node.name === undefined) return;
      if (
        !(ts.getModifiers(node) ?? []).some(
          (m) => m.kind === ts.SyntaxKind.ExportKeyword,
        )
      )
        return;
      if (!exported.has(node.name.text)) return;

      const parameters = node.parameters
        .map((p) => p.getText(source).replace(/\s+/g, " "))
        .join(", ");
      const returns = node.type
        ? `: ${node.type.getText(source).replace(/\s+/g, " ")}`
        : "";
      const doc = ts
        .getJSDocCommentsAndTags(node)
        .map((d) => (typeof d.comment === "string" ? d.comment : ""))
        .join("\n");

      entries.push({
        signature: `${node.name.text}(${parameters})${returns}`,
        summary: firstParagraph(doc),
      });
    });
  }

  return entries;
}

function pythonFunctions(
  path: string,
  indent: string,
  only?: ReadonlySet<string>,
): SdkEntry[] {
  const text = read(path);
  const pattern = new RegExp(
    `^${indent}def ([a-z][a-z0-9_]*)\\(([\\s\\S]*?)\\)(\\s*->\\s*[^:]+)?:\\n\\s*"""([\\s\\S]*?)"""`,
    "gm",
  );
  const entries: SdkEntry[] = [];

  for (const match of text.matchAll(pattern)) {
    const name = match[1] ?? "";
    if (only !== undefined && !only.has(name)) continue;

    const parameters = (match[2] ?? "")
      .split(",")
      .map((p) => p.replace(/\s+/g, " ").trim())
      .filter((p) => p !== "" && p !== "self")
      .join(", ");
    const returns = (match[3] ?? "").replace(/\s+/g, " ").trim();

    entries.push({
      signature: `${name}(${parameters})${returns === "" ? "" : ` ${returns}`}`,
      summary: firstParagraph((match[4] ?? "").replace(/``/g, "`")),
    });
  }

  return entries;
}

function pythonExportedFunctions(): SdkEntry[] {
  const init = read("python/parmana/crypto/__init__.py");
  const exported = new Set(
    [...init.matchAll(/"([a-z][a-z0-9_]*)"/g)].map((m) => m[1] ?? ""),
  );

  return [
    "python/parmana/crypto/offline_verifier.py",
    "python/parmana/crypto/step_up.py",
    "python/parmana/crypto/approval.py",
    "python/parmana/crypto/release.py",
    "python/parmana/crypto/canonical.py",
  ].flatMap((path) => pythonFunctions(path, "", exported));
}

function sdkTable(entries: readonly SdkEntry[]): string[] {
  return [
    "| Signature | What it does |",
    "| --------- | ------------ |",
    ...entries.map(
      (entry) => `| \`${cell(entry.signature)}\` | ${entry.summary || " "} |`,
    ),
    "",
  ];
}

function sdkChapter(): GeneratedChapter {
  const tsMethods = typescriptClientMethods();
  const pyMethods = pythonFunctions("python/parmana/client.py", "    ");

  const lines = [
    frontMatter(
      "Reference: every SDK method",
      "Every method of ParmanaClient in the TypeScript and Python SDKs, and every signing and verifying function they export, generated from the SDK source.",
    ),
    HEADER_NOTE,
    "",
    "Read from the SDK source with each method's own doc comment: `typescript/src/client/ParmanaClient.ts` and `python/parmana/client.py`. A method added to either client appears here the next time the reference is generated, and a test fails until it is. Configuration, retries and errors: [TypeScript](/sdks/typescript-configuration) and [Python](/sdks/python-configuration).",
    "",
    "## TypeScript: `ParmanaClient` (`@parmana/sdk`)",
    "",
    ...sdkTable(tsMethods),
    "## TypeScript: functions exported next to the client",
    "",
    "They make no request.",
    "",
    ...sdkTable(typescriptExportedFunctions()),
    "## Python: `ParmanaClient` (`parmana`)",
    "",
    ...sdkTable(pyMethods),
    "## Python: functions in `parmana.crypto`",
    "",
    'They make no request. Install with `pip install "parmana[verify]"`.',
    "",
    ...sdkTable(pythonExportedFunctions()),
  ];

  return {
    file: `${BUILD_BOOK_DIRECTORY}/reference-sdk.mdx`,
    content: lines.join("\n"),
  };
}

// -----------------------------------------------------------------------------
// Error codes
// -----------------------------------------------------------------------------

interface ErrorEntry {
  readonly statuses: Set<string>;
  readonly operations: Set<string>;
  message: string;
}

/**
 * Every error class in the server source whose constructor calls
 * super("<CODE>", ..., <status>): the code and HTTP status it declares.
 */
function errorClasses(): Map<string, { status?: string; source: string }> {
  const found = new Map<
    string,
    { status?: string; source: string; className?: string }
  >();
  const classes = new Map<string, { parent?: string; status?: string }>();
  const roots = ["packages"];
  const files: string[] = [];

  const walk = (dir: string): void => {
    for (const entry of readdirSync(join(repoRoot, dir), {
      withFileTypes: true,
    })) {
      const path = `${dir}/${entry.name}`;

      if (entry.isDirectory()) {
        if (["node_modules", "dist", "tests", "test"].includes(entry.name))
          continue;
        walk(path);
      } else if (
        entry.name.endsWith(".ts") &&
        !entry.name.endsWith(".d.ts") &&
        path.includes("/src/")
      ) {
        files.push(path);
      }
    }
  };

  roots.forEach(walk);

  for (const path of files) {
    const text = read(path);
    if (!text.includes("super(") && !text.includes("code:")) continue;

    const source = ts.createSourceFile(
      path,
      text,
      ts.ScriptTarget.Latest,
      true,
    );

    const visit = (node: ts.Node): void => {
      if (ts.isClassDeclaration(node) && node.name !== undefined) {
        const parent = node.heritageClauses
          ?.find((h) => h.token === ts.SyntaxKind.ExtendsKeyword)
          ?.types[0]?.expression.getText(source);
        classes.set(node.name.text, {
          ...(parent !== undefined ? { parent } : {}),
          ...(classes.get(node.name.text)?.status !== undefined
            ? { status: classes.get(node.name.text)?.status }
            : {}),
        });
      }

      if (
        ts.isCallExpression(node) &&
        node.expression.kind === ts.SyntaxKind.SuperKeyword &&
        node.arguments.length >= 2
      ) {
        let owner: ts.Node | undefined = node.parent;
        while (owner !== undefined && !ts.isClassDeclaration(owner))
          owner = owner.parent;
        const ownerName =
          owner !== undefined && ts.isClassDeclaration(owner)
            ? owner.name?.text
            : undefined;
        const numeric = node.arguments.find((a): a is ts.NumericLiteral =>
          ts.isNumericLiteral(a),
        );
        if (ownerName !== undefined && numeric !== undefined) {
          classes.set(ownerName, {
            ...classes.get(ownerName),
            status: numeric.text,
          });
        }

        // ParmanaError subclasses pass the code first; RuntimeError
        // subclasses pass (message, status, code). Take whichever argument
        // is a literal in the form of a code.
        const code = node.arguments
          .map((argument) =>
            ts.isStringLiteral(argument) ||
            ts.isNoSubstitutionTemplateLiteral(argument)
              ? argument.text
              : undefined,
          )
          .find(
            (text) =>
              text !== undefined &&
              /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/.test(text),
          );

        if (
          code !== undefined &&
          /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/.test(code)
        ) {
          const status = node.arguments
            .slice(1)
            .find((a): a is ts.NumericLiteral => ts.isNumericLiteral(a));

          if (!found.has(code)) {
            found.set(code, {
              ...(status !== undefined ? { status: status.text } : {}),
              source: path,
              ...(ownerName !== undefined ? { className: ownerName } : {}),
            });
          }
        }
      }

      // A route answering inline: res.status(<N>).json({ ..., code: "<CODE>" }),
      // where code and status may each be `condition ? a : b`, paired in order.
      if (
        ts.isPropertyAssignment(node) &&
        ts.isIdentifier(node.name) &&
        node.name.text === "code"
      ) {
        const literal = (e: ts.Expression): string | undefined =>
          (ts.isStringLiteral(e) || ts.isNoSubstitutionTemplateLiteral(e)) &&
          /^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+$/.test(e.text)
            ? e.text
            : undefined;
        const codes = ts.isConditionalExpression(node.initializer)
          ? [
              literal(node.initializer.whenTrue),
              literal(node.initializer.whenFalse),
            ]
          : [literal(node.initializer)];

        let parent: ts.Node | undefined = node.parent;
        let statuses: Array<string | undefined> = [];

        while (parent !== undefined && !ts.isStatement(parent)) {
          if (
            ts.isCallExpression(parent) &&
            ts.isPropertyAccessExpression(parent.expression) &&
            parent.expression.name.text === "json" &&
            ts.isCallExpression(parent.expression.expression) &&
            ts.isPropertyAccessExpression(
              parent.expression.expression.expression,
            ) &&
            parent.expression.expression.expression.name.text === "status"
          ) {
            const argument = parent.expression.expression.arguments[0];
            const numeric = (e: ts.Expression): string | undefined =>
              ts.isNumericLiteral(e) ? e.text : undefined;
            if (argument !== undefined) {
              statuses = ts.isConditionalExpression(argument)
                ? [numeric(argument.whenTrue), numeric(argument.whenFalse)]
                : [numeric(argument)];
            }
            break;
          }
          parent = parent.parent;
        }

        codes.forEach((code, i) => {
          const status = statuses.length === 1 ? statuses[0] : statuses[i];
          if (code !== undefined && status !== undefined && !found.has(code)) {
            found.set(code, { status, source: path });
          }
        });
      }

      ts.forEachChild(node, visit);
    };

    visit(source);
  }

  for (const entry of found.values()) {
    let name = entry.className;
    const seen = new Set<string>();

    while (
      entry.status === undefined &&
      name !== undefined &&
      !seen.has(name)
    ) {
      seen.add(name);
      const info = classes.get(name);
      if (info?.status !== undefined && name !== entry.className)
        entry.status = info.status;
      name = info?.parent;
    }
  }

  return found;
}

interface ErrorEntry {
  readonly statuses: Set<string>;
  readonly operations: Set<string>;
  message: string;
  source: string;
}

function errorsChapter(): GeneratedChapter {
  const spec = parse(read("openapi/openapi.bundled.yaml")) as {
    paths: Record<
      string,
      Record<
        string,
        { operationId?: string; responses?: Record<string, unknown> }
      >
    >;
  };
  const errors = new Map<string, ErrorEntry>();
  const entryFor = (code: string): ErrorEntry => {
    const existing = errors.get(code);
    if (existing !== undefined) return existing;
    const created: ErrorEntry = {
      statuses: new Set(),
      operations: new Set(),
      message: "",
      source: "",
    };
    errors.set(code, created);
    return created;
  };

  // 1. Every code in a real captured response.
  for (const operations of Object.values(spec.paths)) {
    for (const operation of Object.values(operations)) {
      if (
        operation?.operationId === undefined ||
        operation.responses === undefined
      )
        continue;

      for (const [status, response] of Object.entries(operation.responses)) {
        const examples =
          (
            response as {
              content?: Record<
                string,
                { examples?: Record<string, { value?: unknown }> }
              >;
            }
          ).content?.["application/json"]?.examples ?? {};

        for (const example of Object.values(examples)) {
          const value = example?.value as
            { code?: unknown; error?: unknown } | undefined;

          if (
            value === undefined ||
            typeof value.code !== "string" ||
            !/^[A-Z][A-Z0-9_]+$/.test(value.code)
          ) {
            continue;
          }

          const entry = entryFor(value.code);
          entry.statuses.add(status);
          entry.operations.add(operation.operationId);
          if (entry.message === "" && typeof value.error === "string")
            entry.message = value.error;
        }
      }
    }
  }

  // 2. Every error class in the server source.
  for (const [code, declared] of errorClasses()) {
    const entry = entryFor(code);
    if (declared.status !== undefined) entry.statuses.add(declared.status);
    entry.source = declared.source;
  }

  // 3. Where a known code is named in a response description.
  const known = new Set(errors.keys());

  for (const operations of Object.values(spec.paths)) {
    for (const operation of Object.values(operations)) {
      if (
        operation?.operationId === undefined ||
        operation.responses === undefined
      )
        continue;

      for (const [status, response] of Object.entries(operation.responses)) {
        const description = (response as { description?: unknown }).description;
        if (typeof description !== "string") continue;

        for (const match of description.matchAll(
          /\b[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)+\b/g,
        )) {
          if (!known.has(match[0])) continue;
          const entry = entryFor(match[0]);
          entry.statuses.add(status);
          entry.operations.add(operation.operationId);
        }
      }
    }
  }

  const sorted = [...errors.entries()].sort(([a], [b]) => a.localeCompare(b));

  const lines = [
    frontMatter(
      "Reference: every error code",
      "Every error code the server can return, with its HTTP status, where it occurs and a real message, generated from the source and the OpenAPI file.",
    ),
    HEADER_NOTE,
    "",
    `Every error code the server declares, ${sorted.length} in all: each error class in \`packages/*/src\` (its code and HTTP status), and each \`code\` in a real captured response in \`openapi/openapi.bundled.yaml\`. An error body is \`{ "error": "<message>", "code": "<CODE>" }\`; a few refusals carry more fields, shown on the operation's page. "Returned by" lists the operations whose documented responses name the code; an empty cell means the code can be returned by any operation that reaches that part of the server. What to do for each class of error: [Errors and troubleshooting](/build-book/09-errors-and-troubleshooting).`,
    "",
    "| Code | HTTP | Returned by | Example message | Declared in |",
    "| ---- | ---- | ----------- | --------------- | ----------- |",
    ...sorted.map(
      ([code, entry]) =>
        `| \`${code}\` | ${[...entry.statuses].sort().join(", ")} | ${[
          ...entry.operations,
        ]
          .sort()
          .map((o) => `\`${o}\``)
          .join(
            ", ",
          )} | ${cell(entry.message)} | ${entry.source === "" ? "" : `\`${entry.source}\``} |`,
    ),
    "",
  ];

  return {
    file: `${BUILD_BOOK_DIRECTORY}/reference-errors.mdx`,
    content: lines.join("\n"),
  };
}

export function buildReferenceChapters(): GeneratedChapter[] {
  return [endpointsChapter(), sdkChapter(), errorsChapter()];
}
